version: '3'
services:
  app:
    container_name: michaelgrigoryan-todo
    restart: always
    build: .
    ports:
      - '80:80'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'